name: lemon
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^7.8.4 
  auto_size_text: ^3.0.0
  dio: ^5.3.4
  dropdown_search: ^5.0.6
  email_validator: ^2.1.17
  expandable_text: ^2.3.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  intl: any
  intl_phone_number_input: ^0.7.4
  json_annotation: ^4.8.1
  mailer: ^6.1.0
  path_provider: ^2.1.1
  pin_code_fields: ^8.0.1
  popover: ^0.2.8+2
  provider: ^6.0.5
  share_plus: ^7.2.1
  shared_preferences: ^2.2.0
  talker_bloc_logger: ^2.2.1
  talker_dio_logger: ^2.3.1
  talker_flutter: ^3.5.4
  tap_debouncer: ^2.2.0
  timeago: ^3.6.1
  web_socket_channel: ^2.4.0
  shimmer: ^3.0.0
  camera: ^0.10.5+9
  torch_light: ^1.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1  
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7
  auto_route_generator: ^7.3.2
  build_runner:

# flutter_native_splash: 
#   image: "assets/images/white_logo.png"
#   background_image: "assets/images/splash.png"

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/logo_dark.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Medium.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Thin.ttf
        
    - family:  CustomIcons
      fonts:
       - asset: assets/fonts/CustomIcons.ttf
